# Generated by Django 3.1.2 on 2021-05-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe_ticket',
            old_name='fecha_inicio',
            new_name='rango_inicio',
        ),
        migrations.RenameField(
            model_name='informe_ticket',
            old_name='fecha_termino',
            new_name='rango_termino',
        ),
        migrations.RemoveField(
            model_name='informe_ticket',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='informe_ticket',
            name='tipo_informe',
            field=models.CharField(default='a', max_length=150, verbose_name='tipo informe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DETALLE_INFORME',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fk_correlativo_inf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.informe_ticket')),
                ('fk_num_boleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.boleta')),
            ],
            options={
                'verbose_name': 'detalle informe',
                'verbose_name_plural': 'detalles de informes',
                'db_table': 'DETALLE_INFORME',
            },
        ),
    ]
