# Generated by Django 3.1.2 on 2021-05-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_auto_20210519_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fk_tipo_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CORE.tipo_ticket'),
        ),
    ]
