# Generated by Django 3.1.2 on 2021-05-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_auto_20210519_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='cargar saldo'),
        ),
    ]
