# Generated by Django 3.1.2 on 2021-05-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0005_auto_20210520_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='clave',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.perfil', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.turno', verbose_name='Turno'),
        ),
    ]
