# Generated by Django 3.1.2 on 2021-05-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0007_empleado_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clave',
            field=models.CharField(max_length=101, verbose_name='contraseña'),
        ),
    ]
