# Generated by Django 3.1.2 on 2021-07-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0008_auto_20210524_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fk_rut_visitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CORE.visitante'),
        ),
    ]
